import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export async function generateTypes(): Promise<string> {
  return compileFromFile(join(root, "schema", "soap-note.schema.json"), {
    bannerComment:
      "/**\n" +
      " * This file was automatically generated from schema/soap-note.schema.json.\n" +
      " * Do not edit this file directly — run `npm run generate:types` instead.\n" +
      " * A CI-enforced drift test (tests/types-drift.test.ts) fails the build if\n" +
      " * this file and the schema fall out of sync.\n" +
      " */",
    style: { singleQuote: false },
    unreachableDefinitions: true,
  });
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const output = await generateTypes();
  writeFileSync(join(root, "src", "types.ts"), output);
  console.log("Generated src/types.ts from schema/soap-note.schema.json");
}
