/**
 * This file was automatically generated from schema/soap-note.schema.json.
 * Do not edit this file directly — run `npm run generate:types` instead.
 * A CI-enforced drift test (tests/types-drift.test.ts) fails the build if
 * this file and the schema fall out of sync.
 */

/**
 * Canonical shape for a structured SOAP (Subjective, Objective, Assessment, Plan) clinical note. This JSON Schema file is the source of truth for the note shape and is usable from any language with a JSON Schema Draft 2020-12 validator — the TypeScript library in this repo (src/validate.ts) is a convenience wrapper around it, not a second source of truth.
 */
export interface SoapNote {
  metadata: NoteMetadata;
  /**
   * Patient-reported information: the reason for the visit and how the patient describes it.
   */
  subjective: {
    /**
     * The primary reason for the encounter, in the patient's own words or a concise clinical summary.
     */
    chiefComplaint: string;
    /**
     * Narrative history of the present illness (HPI).
     */
    historyOfPresentIllness?: string;
    /**
     * Structured review-of-systems findings.
     */
    reviewOfSystems?: ReviewOfSystemsFinding[];
  };
  /**
   * Clinician-observed and measured information.
   */
  objective: {
    vitals?: Vitals;
    /**
     * Structured physical exam findings, grouped by body system.
     */
    examFindings?: ExamFinding[];
  };
  /**
   * Problem/diagnosis list for this encounter.
   */
  assessment: Problem[];
  /**
   * Plan items for this encounter: medications, orders, referrals, follow-ups, patient education.
   */
  plan: PlanItem[];
}
/**
 * Encounter-level metadata for a SOAP note. Intentionally carries no direct patient identifier — `patientRef` is an opaque, caller-defined reference string. Resolving that reference to an actual patient identity (name, DOB, MRN) is the responsibility of the consuming application, not this schema.
 */
export interface NoteMetadata {
  /**
   * Type of encounter this note documents, e.g. primary-care-followup, urgent-care, telehealth-checkin.
   */
  encounterType: string;
  /**
   * Role of the note's author, e.g. physician, nurse-practitioner, physician-assistant.
   */
  authorRole: string;
  /**
   * ISO 8601 timestamp for when the note was authored.
   */
  timestamp: string;
  /**
   * Opaque, caller-defined reference to the patient this note belongs to (e.g. an internal record ID). MUST NOT be a direct identifier such as a name, date of birth, or MRN — identity resolution is the caller's responsibility.
   */
  patientRef?: string;
}
/**
 * This interface was referenced by `SoapNote`'s JSON-Schema
 * via the `definition` "reviewOfSystemsFinding".
 */
export interface ReviewOfSystemsFinding {
  /**
   * Body system reviewed, e.g. cardiovascular, respiratory, gastrointestinal.
   */
  system: string;
  /**
   * Free-text description of the finding, if any.
   */
  finding?: string;
  status: "positive" | "negative" | "not-assessed";
}
/**
 * Vital sign measurements captured during an encounter. Every field is optional and independent — callers should include only the vitals actually captured; do not assume all are present.
 */
export interface Vitals {
  /**
   * Systolic/diastolic blood pressure.
   */
  bloodPressure?: {
    systolic?: Measurement;
    diastolic?: Measurement;
  };
  heartRate?: Measurement;
  temperature?: Measurement;
  respiratoryRate?: Measurement;
  spo2?: Measurement;
  height?: Measurement;
  weight?: Measurement;
}
/**
 * A single measured value with its unit. Unit is required so a bare number is never ambiguous (e.g. lb vs kg, F vs C).
 *
 * This interface was referenced by `Vitals`'s JSON-Schema
 * via the `definition` "measurement".
 */
export interface Measurement {
  value: number;
  unit: string;
}
/**
 * This interface was referenced by `SoapNote`'s JSON-Schema
 * via the `definition` "examFinding".
 */
export interface ExamFinding {
  /**
   * Body system examined, e.g. cardiovascular, respiratory, musculoskeletal.
   */
  bodySystem: string;
  /**
   * Free-text description of the exam finding.
   */
  finding: string;
}
/**
 * This interface was referenced by `SoapNote`'s JSON-Schema
 * via the `definition` "problem".
 */
export interface Problem {
  /**
   * Description of the problem or diagnosis.
   */
  description: string;
  status: "active" | "resolved" | "chronic";
  codedConcept?: CodedConcept;
}
/**
 * Optional coded reference (e.g. ICD-10-CM, SNOMED CT). Not required — notes without coding applied yet must still validate.
 */
export interface CodedConcept {
  /**
   * URI identifying the coding system this code belongs to, e.g. http://hl7.org/fhir/sid/icd-10-cm or http://snomed.info/sct.
   */
  system: string;
  /**
   * The code value within `system`.
   */
  code: string;
  /**
   * Human-readable display text for the code.
   */
  display: string;
}
/**
 * This interface was referenced by `SoapNote`'s JSON-Schema
 * via the `definition` "planItem".
 */
export interface PlanItem {
  category: "medication" | "order" | "referral" | "followUp" | "patientEducation";
  /**
   * Free-text detail for this plan item.
   */
  detail: string;
}
